CREATE TABLE IF NOT EXISTS `dailyquote` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`quote`	TEXT NOT NULL,
	`author`	TEXT NOT NULL
);
INSERT INTO `dailyquote` (quote,author) VALUES ('Another world is not only possible, she is on her way. On a quiet day, I can hear her breathing.','Arundhati Roy'),
 ('I am determined to be cheerful and happy in whatever situation I may find myself. For I have learned that the greater part of our happiness or misery depends on our disposition and not our circumstances.','Martha Washington'),
 ('Don''t be humble. You''re not that great.','Golda Meir'),
 ('Learn from the mistakes of others. You can’t live long enough to make them all yourself.','Eleanor Roosevelt'),
 ('Earn your leadership every day.','Michael Jordan'),
 ('You don’t lead by hitting people over the head—that’s assault, not leadership.','Dwight Eisenhower'),
 ('My responsibility is getting all my players playing for the name on the front of the jersey, not the one on the back.','Unknown'),
 ('There are three essentials to leadership: humility, clarity and courage.','Fuchan Yuan'),
 ('A good leader is a person who takes a little more than his share of the blame and a little less than his share of the credit.','John Maxwell'),
 ('Whatever you are, be a good one.','Abraham Lincoln'),
 ('Not the cry, but the flight of a wild duck, leads the flock to fly and follow.','Chinese Proverb'),
 ('What you do has far greater impact than what you say.','Stephen Covey'),
 ('Lead and inspire people. Don’t try to manage and manipulate people. Inventories can be managed but people must be lead.','Ross Perot'),
 ('If your actions inspire others to dream more, learn more, do more and become more, you are a leader.','John Quincy Adams'),
 ('Do what you feel in your heart to be right–for you’ll be criticized anyway.','Eleanor Roosevelt'),
 ('As we look ahead into the next century, leaders will be those who empower others.','Bill Gates'),
 ('A man who wants to lead the orchestra must turn his back on the crowd.','Max Lucado'),
 ('A ruler should be slow to punish and swift to reward.','Ovid'),
 ('The key to successful leadership today is influence, not authority.','Kenneth Blanchard'),
 ('The art of leadership is saying no, not saying yes. It is very easy to say yes.','Tony Blair'),
 ('So much of what we call management consists in making it difficult for people to work.','Peter Drucker'),
 ('People buy into the leader before they buy into the vision.','John Maxwell'),
 ('To command is to serve, nothing more and nothing less.','Andre Malraux'),
 ('Never doubt that a small group of thoughtful, concerned citizens can change world. Indeed it is the only thing that ever has.','Margaret Mead'),
 ('A leader is one who knows the way, goes the way, and shows the way.','John Maxwell'),
 ('The first responsibility of a leader is to define reality. The last is to say thank you. In between, the leader is a servant.','Max DePree'),
 ('A leader is best when people barely know he exists, when his work is done, his aim fulfilled, they will say: we did it ourselves.','Lao Tzu'),
 ('If you don''t go after what you want you''ll never have it.','Nora Roberts'),
 ('I’d rather regret the things I’ve done than regret the things I haven’t done.','Lucille Ball'),
 ('Growth and comfort never coexist.','Ginni Rometty'),
 ('Don''t be trapped by your own assumptions.','Nicole Curtis');
